# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_nc_dss": "02_data.news_commentary.ipynb",
         "get_tatoeba_dss": "02_data.tatoeba.ipynb",
         "generate_from_strs": "03a_models.patch.ipynb",
         "gen_attention_mask": "03c_models.bert2gpt2.ipynb",
         "BertEncoder": "03c_models.bert2gpt2.ipynb",
         "GPT2Decoder": "03c_models.bert2gpt2.ipynb",
         "Bert2GPT2": "03c_models.bert2gpt2.ipynb",
         "GeneratedBert2GPT2": "03c_models.bert2gpt2.ipynb",
         "generate_from_ids": "03c_models.tran2tran.ipynb",
         "GRUEncoder": "03c_models.gru2gru.ipynb",
         "GRUDecoder": "03c_models.gru2gru.ipynb",
         "GRU2GRU": "03c_models.gru2gru.ipynb",
         "GeneratedGRU2GRU": "03c_models.gru2gru.ipynb",
         "QRNNEncoder": "03c_models.qrnn2qrnn.ipynb",
         "QRNNDecoder": "03c_models.qrnn2qrnn.ipynb",
         "CrossAttnQRNNLayer": "03c_models.qrnn2qrnn.ipynb",
         "CrossAttnQRNN": "03c_models.qrnn2qrnn.ipynb",
         "CrossAttnQRNNDecoder": "03c_models.qrnn2qrnn.ipynb",
         "QRNN2QRNN": "03c_models.qrnn2qrnn.ipynb",
         "QRNN2AttnQRNN": "03c_models.qrnn2qrnn.ipynb",
         "GeneratedQRNN2QRNN": "03c_models.qrnn2qrnn.ipynb",
         "GeneratedQRNN2AttnQRNN": "03c_models.qrnn2qrnn.ipynb",
         "QRNN2QRNNCallback": "03c_models.qrnn2qrnn.ipynb",
         "WPEmbed": "03c_models.tran2tran.ipynb",
         "TranEncoder": "03c_models.tran2tran.ipynb",
         "TranDecoder": "03c_models.tran2tran.ipynb",
         "Tran2Tran": "03c_models.tran2tran.ipynb",
         "GeneratedTran2Tran": "03c_models.tran2tran.ipynb",
         "compute_bleu": "04_metrics.ipynb"}

modules = ["data/news_commentary.py",
           "data/tatoeba.py",
           "models/patch.py",
           "models/bert2gpt2.py",
           "models/gru2gru.py",
           "models/qrnn2qrnn.py",
           "models/tran2tran.py",
           "metrics.py"]

doc_url = "https://cwza.github.io/nmt_try/"

git_url = "https://github.com/cwza/nmt_try/tree/master/"

def custom_doc_links(name): return None
