# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03a_models.patch.ipynb (unless otherwise specified).

__all__ = ['generate_from_strs']

# Cell
from transformers import AutoTokenizer
from fastai2.basics import *

from fastai_transformers_utils.generated_lm import GenerateArgs
from fastai_transformers_utils.tokenizers import GPT2DecoderTokenizer

from .gru2gru import GeneratedGRU2GRU, GRUEncoder, GRUDecoder, GRU2GRU
from .tran2tran import GeneratedTran2Tran, TranEncoder, TranDecoder, Tran2Tran
from .bert2gpt2 import BertEncoder, GPT2Decoder, Bert2GPT2, GeneratedBert2GPT2

# Cell
@patch
@torch.no_grad()
def generate_from_strs(self: [GeneratedTran2Tran, GeneratedGRU2GRU, GeneratedBert2GPT2], src_strs, generate_args: GenerateArgs, device):
    ''' self.seq2seq.eval, self.enc_tokenizer.encode, self.dec_tokenizer.decode, self.generate_from_ids '''
    self.seq2seq.eval()

    pred_strs = []
    for src_str in src_strs:
        src_id = self.enc_tokenizer.encode(src_str)
        src_ids = torch.tensor([src_id], device=device)
        pred_ids = self.generate_from_ids(src_ids, generate_args)
        pred_str = self.dec_tokenizer.decode(pred_ids[0], skip_special_tokens=True)
        pred_strs.append(pred_str)
    return pred_strs