# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_tatoeba_dss": "02_data.tatoeba.ipynb",
         "generate_from_strs": "03a_models.patch.ipynb",
         "gen_attention_mask": "03c_models.bert2gpt2.ipynb",
         "BertEncoder": "03c_models.bert2gpt2.ipynb",
         "BatchFirstMultiheadAttention": "03c_models.bert2gpt2.ipynb",
         "CrossAttention": "03c_models.bert2gpt2.ipynb",
         "GPT2Decoder": "03c_models.bert2gpt2.ipynb",
         "Bert2GPT2": "03c_models.bert2gpt2.ipynb",
         "GeneratedBert2GPT2": "03c_models.bert2gpt2.ipynb",
         "generate_from_ids": "03c_models.tran2tran.ipynb",
         "GRUEncoder": "03c_models.gru2gru.ipynb",
         "GRUDecoder": "03c_models.gru2gru.ipynb",
         "GRU2GRU": "03c_models.gru2gru.ipynb",
         "GeneratedGRU2GRU": "03c_models.gru2gru.ipynb",
         "WPEmbed": "03c_models.tran2tran.ipynb",
         "TranEncoder": "03c_models.tran2tran.ipynb",
         "TranDecoder": "03c_models.tran2tran.ipynb",
         "Tran2Tran": "03c_models.tran2tran.ipynb",
         "GeneratedTran2Tran": "03c_models.tran2tran.ipynb",
         "compute_bleu": "04_metrics.ipynb"}

modules = ["data/tatoeba.py",
           "models/patch.py",
           "models/bert2gpt2.py",
           "models/gru2gru.py",
           "models/tran2tran.py",
           "metrics.py"]

doc_url = "https://cwza.github.io/nmt_small/"

git_url = "https://github.com/cwza/nmt_small/tree/master/"

def custom_doc_links(name): return None
